apiVersion: apps/v1
kind: Deployment

metadata:
  name: test
  labels:
    app: test

spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test-container
          image: k8s.gcr.io/busybox
          command: [ "/bin/sh", "-c", "echo $(MESSAGE)" ]
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: MESSAGE
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: dev-config
                  key: ENV
